/**
 * AUTO-GENERATED by scripts/gen-authorised.mjs from architecture/demand/demand-map.csv.
 * Do not edit by hand — edit the demand map and regenerate.
 *
 * Keystone v3.2 Part 6A: a page is earned by evidence of demand. These are the
 * geographies and (geo, service) tuples that cleared the two-signal gate. A route
 * may only link to what is in here; everything else is areaServed prose.
 *
 * Generated 2026-09-25 · 10 city pages · 35 city x service pages · 31 declined cities.
 */
export const AUTHORISED_CITIES: readonly string[] = [
  "anacortes",
  "bellingham",
  "birch-bay",
  "blaine",
  "burlington",
  "everson",
  "ferndale",
  "lynden",
  "mount-vernon",
  "sudden-valley"
] as const;

export const AUTHORISED_TUPLES: Readonly<Record<string, readonly string[]>> = {
  "bellingham": [
    "gutter-cleaning",
    "house-washing",
    "moss-removal",
    "pressure-washing",
    "roof-cleaning",
    "solar-panel-cleaning",
    "window-cleaning"
  ],
  "ferndale": [
    "gutter-cleaning",
    "house-washing",
    "roof-cleaning",
    "window-cleaning"
  ],
  "lynden": [
    "gutter-cleaning",
    "house-washing",
    "roof-cleaning",
    "window-cleaning"
  ],
  "blaine": [
    "gutter-cleaning",
    "house-washing",
    "roof-cleaning",
    "window-cleaning"
  ],
  "burlington": [
    "gutter-cleaning",
    "house-washing",
    "roof-cleaning",
    "window-cleaning"
  ],
  "anacortes": [
    "gutter-cleaning",
    "house-washing",
    "roof-cleaning",
    "window-cleaning"
  ],
  "everson": [
    "gutter-cleaning",
    "house-washing",
    "roof-cleaning",
    "window-cleaning"
  ],
  "sudden-valley": [
    "gutter-cleaning",
    "house-washing",
    "roof-cleaning",
    "window-cleaning"
  ]
} as const;

/** Declined geographies — named in coverage copy and areaServed, never linked. */
export const DECLINED_CITIES: readonly string[] = [
  "acme",
  "alger",
  "bay-view",
  "big-lake",
  "bow",
  "clear-lake",
  "concrete",
  "conway",
  "custer",
  "deming",
  "edison",
  "geneva",
  "glacier",
  "guemes-island",
  "hamilton",
  "kendall",
  "la-conner",
  "lummi-island",
  "lyman",
  "maple-falls",
  "marietta",
  "nooksack",
  "oak-harbor",
  "point-roberts",
  "rockport",
  "samish-island",
  "sedro-woolley",
  "semiahmoo",
  "sumas",
  "van-zandt",
  "wickersham"
] as const;

export const isAuthorisedCity = (geo: string): boolean => AUTHORISED_CITIES.includes(geo);
export const isAuthorisedTuple = (geo: string, service: string): boolean =>
  (AUTHORISED_TUPLES[geo] ?? []).includes(service);
/** Markets that carry this service AND cleared the gate for it. */
export const marketsForService = (service: string): string[] =>
  Object.keys(AUTHORISED_TUPLES).filter((g) => AUTHORISED_TUPLES[g].includes(service)).sort();
